version: '3.8'

services:
  fitness-app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=your-db-username
      - DB_PASSWORD=your-db-password
      - DB_NAME=your-db-name
  db:
    image: postgres:13.2-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"